### ISSUE TITLE
[IMPROVEMENT] UI changes 

### ISSUE THREAD

**Issue by NishantSinghal19** [CCExtractor/taskwarrior-flutter#12]
Your ideas regarding UI changes will be appreciated

**Comment by bhav-khurana** [comment]
![IMG_20221001_010716.jpg](https://user-images.githubusercontent.com/96694482/193344304-977d3c60-b5e7-475d-ab4e-bae2283d8624.jpg)


We currently have 2 separate tiles "Profile" and "Select Profile". Clicking on the former one doesn't do anything, so it would be better if we merge these two into a single tile so that whenever the user clicks on the tile, he gets a drop-down to change the profile and the plus button would add a new one.

**Comment by piyushkumar12111111** [comment]
Please assign me this issue

**Comment by NishantSinghal19** [comment]
@bhav-khurana khurana i am assigning you this issue and then you can give me pr

**Comment by bhav-khurana** [comment]
> @bhav-khurana khurana i am assigning you this issue and then you can give me pr

Sure sir

**Comment by bhav-khurana** [comment]
> @bhav-khurana khurana i am assigning you this issue and then you can give me pr

I have made a PR for this issue

**Comment by kunal-iitj** [comment]
![image](https://user-images.githubusercontent.com/105335204/205841996-b321cddc-997a-4821-bdb5-4e4d4ff029cb.png)
There should be some padding between the cursor and the boundary of the search field.

**Comment by kunal-iitj** [comment]
I have made opened a PR fixing this issue
Could you please review the PR
