### ISSUE TITLE
[UI] Remove the checkboxTile feature

### ISSUE THREAD

**Issue by stuck-in-a-conundrum** [CCExtractor/taskwarrior-flutter#120]
This feature marks the tasks as completed on a single click. Due to this, accidental clicks can hinder the user experience. 
As sliding the tile will mark the task as completed,  single tap becomes redundant. The feature can be removed altogether, and the details page can be opened on a single tap

**Comment by ZapeeoSheikh** [comment]
@stuck-in-a-conundrum Please assign me this issue, I am working to fixing this issue right now.

**Comment by ZapeeoSheikh** [comment]
I have send a PR #122 in which I have fixed the issues of single tap details. 
By wrapping with Ignore Pointer, now we don't need to remove checkbox tile because our screen is navigating to the detail page with the single click as well. Before this Inkwell is not invoking the single tap properly.  

Please review it to merge the changes.

**Comment by virajbhartiya** [comment]
I have submitted a PR #134 in which I have removed the checkbox altogether so that accidental clicks won't disturb users' experience.
Please review it.
