### ISSUE TITLE
Feature request: Be able to specify data directory

### ISSUE THREAD

**Issue by jfab20** [CCExtractor/taskwarrior-flutter#214]
I don't sync my taskwarrior with a taskserver. Instead I use syncthing so sync my taskdata directory between my devices. This works great between my computers, but I can't seem to find a way to make it work with the taskwarrior app in android. 

I tried to paste ```data.location=/path/to/taskdata/``` where you specify your taskrc, but it didn't work. I think this should be a feature because at the end of the day the taskdata is stored *somewhere* so allowing the user to specify where should be a nice feature.

**Comment by andnig** [comment]
This would be tremendously helpful.

Thanks for this app by the way!

**Comment by zillydev** [comment]
I would like to work on this issue.

**Comment by zillydev** [comment]
I researched the codebase and came up with two approaches for this issue.

One approach is adding a 'Select directory' option under 'Manage selected profile', which lets the user pick a directory, which will copy and paste the existing data of that profile in that directory. Further data modifications in that profile will also be made in that directory.
But this would require changing a significant portion of the code, as many functions use the ancestor 'profiles/' directory to navigate between profiles.

Another approach that can be implemented is adding a more general 'Select directory' option that would change the base path of the entire application, thus requiring significantly less code changes.

It would be really helpful to receive inputs so that I can start working on this.

**Comment by zillydev** [comment]
@Pavel401 I would be grateful for inputs on which approach to go with so I can start working on this.

**Comment by Pavel401** [comment]
> I don't sync my taskwarrior with a taskserver. Instead I use syncthing so sync my taskdata directory between my devices. This works great between my computers, but I can't seem to find a way to make it work with the taskwarrior app in android.
> 
> I tried to paste `data.location=/path/to/taskdata/` where you specify your taskrc, but it didn't work. I think this should be a feature because at the end of the day the taskdata is stored _somewhere_ so allowing the user to specify where should be a nice feature.

Do you think we need per-profile directory management or a global select directory?

**Comment by andnig** [comment]
From my personal perspective I think a global setting is enough. No need for per-profile directory. I think the main use case is to put the directory somewhere where also other apps (like termux) have access to - like the sdcard.

**Comment by Pavel401** [comment]
@zillydev go with the second approach.
