### ISSUE TITLE
TaskWarrior v3

### ISSUE THREAD

**Issue by sternj** [CCExtractor/taskwarrior-flutter#347]
TaskWarrior has recently deprecated `taskd` and switched to [taskchampion-sync-server](https://github.com/GothenburgBitFactory/taskchampion-sync-server). I don't know much about taskd or taskwarrior, but is there any chance for support for this new sync server?

**Comment by Pavel401** [comment]
Yes, we will work on this.

**Comment by QuantumBJump** [comment]
does this work only for taskchampion-sync-server, or would this also work with TW3's new recommended sync method of using a GCP bucket?

**Comment by Darukutsu** [comment]
I can't make this work with default config, I get error:
`Server or credentials are missing in taskrc file`
```
sync.server.origin=http:\/\/192.168.0.100:53589
sync.server.client_id=<some_uuid>
sync.encryption_secret=<some_secret>
recurrence=0
```

**Comment by Pavel401** [comment]
@its-me-abhishek Are you working on this?

**Comment by its-me-abhishek** [comment]
I have tested this locally, and it is working fine, i think @Darukutsu may have missed some points:
in /lib/api_service.dart, you need to change: 

```
String baseUrl = 'http://YOUR_IP:8000'; (for API) // note:  if using linux or wsl for directly running the API, you can get the IP by running ifconfig… may use the docker IP if you’re using the Docker container for backend.. 
String origin = http://localhost:8080 (for taskchampion-sync-server container, directly from the source)
``` 

to some deployed values for using it on a mobile device, you may use the same containers/config as [ccsync](https://github.com/its-me-abhishek/ccsync/tree/main) for development purposes, deploy the backend and sync-server container if you want to access the API + server anywhere. For development purposes, we can set up it using Docker with minimal changes to the backend `.env` file as mentioned in the README.md, to set up sync. Additionally, you will have to update your Taskwarrior config on your pc to have a `sync.server.origin` value as the same link that points to the same container that the app uses (the one you will set above in `api_service.dart`)... 

side note: I think that you are using taskd for syncing, or are using Taskwarrior < 3.0, as the error says: Error:Server or credentials are missing in taskrc file but they are not needed in TW3.0 now, 53589 port suggests a taskd container, or I might be wrong..

**Comment by Darukutsu** [comment]
@its-me-abhishek if i understand correctly I have to setup ccsync to be able to use this app with taskwarrior >= 3.0? When enabling toggle, it doesn't refreshes menu so I wasn't able to see CCsync credentials at first, that's why I was importing config to TASKRC which seemed natural because that's same thing I did on computer and it works. Do you plan to add option in menu to configure taskchampion-sync-server url or better parse config for 3.0 and above?

> ...53589 port suggests a taskd container...
nono, that's because I run taskchampion-sync-server as systemd service and this is default set on arch by using `-p` argument

**Comment by its-me-abhishek** [comment]
> if i understand correctly I have to setup ccsync to be able to use this app with taskwarrior >= 3.0?

Yep, you're right. The CCSync backend acts as a middle-ware for syncing/modifying tasks via the taskchampion-sync-server to your app/website, by running a series of commands for everything...

> When enabling toggle, it doesn't refreshes menu so I wasn't able to see CCsync credentials at first

This seems to be a bug, I will look into it, and try to find a fix, thanks.

> Do you plan to add option in menu to configure taskchampion-sync-server url or better parse config for 3.0 and above?

I have planned of implementing configurable url for taskchampion-sync-server on backend, have thought of adding an option under CCSync credentials for: `default url` or `custom server url value`... for the sync server. Will work on this after completing the refactoring of backend... as this will require some testing

**Comment by sternj** [comment]
I'm not too big a fan of having to rebuild the app to use this, is there a new tracking issue for a production-ready v3?

**Comment by martiege** [comment]
I'm sorry this isn't the place to ask this, but is the steps needed to get this to work documented somewhere? I didn't really understand which steps to do in order to get this to work. My understanding is: 

1. Compile a custom version of this repo and install that on my phone
2. Set up an instance of ccsync on my server
3. Connect ccsync to my taskchampion-sync-server
4. Connect my phone to the ccsync-instance 

Is this correct? 

I tried to get into the slack-channel linked a few places here, but it seems like the link expired.

**Comment by its-me-abhishek** [comment]
Hey @martiege! You can find the documentation here: https://its-me-abhishek.github.io/ccsync-docs/

**Comment by trev-dev** [comment]
Hey @its-me-abhishek here comes another necro bump, sorry. It's unclear to me what version of Taskwarrior the android release (v2.0.0 at the time of this question) supports. Also ,is CCSync required for Taskwarrior 3 syncing or can I just use my .taskrc with my task champion server already on board?

**Comment by its-me-abhishek** [comment]
Currently both TW 2.0+ and 3.0+ are supported by the app. To switch between TW2.0 and TW 3.0 you can visit the settings. Although for that version you'll probably have to build a release using Flutter yourself, as TW3.0 is in the latest version. Also, yes, CCSync is essential for Taskwarrior 3 as it has the main API that acts as a pseudo TW3.0+ client on the behalf of your App client, so that you can manage your tasks via the same task-champion-sync-server on both App/Web and your CLI based clients

**Comment by trev-dev** [comment]
I see! Is there some reason why we decided to add another mandatory dependency into the taskwarrior sync mix? It already feels like a 'thing' to have to launch a taskchampion server.
