### ISSUE TITLE
Please clarify author and license of four commits

### ISSUE THREAD

**Issue by bradyt** [CCExtractor/taskwarrior-flutter#58]
Can you please clarify who is author for the following four commits, and what the license for them is?

- 1451d825f67219fadb0a93af4554456c29ba9478
- e0b5f0811c0835f4834ad5a29d611949f5bf288d
- 29280fc48bbd255fd3a40a48ceaf7eefed5e3a93
- 3d8f3e49f636b4d2e29d68be35f50ad942ec8e72

**Comment by bradyt** [comment]
@NishantSinghal19, please see above.

**Comment by NishantSinghal19** [comment]
I made the commits, 
> * [1451d82](https://github.com/CCExtractor/taskwarrior-flutter/commit/1451d825f67219fadb0a93af4554456c29ba9478) -  I have taken some reference from your code, so I will happy to change in license to acknowledge you if you want.
> * [e0b5f08](https://github.com/CCExtractor/taskwarrior-flutter/commit/e0b5f0811c0835f4834ad5a29d611949f5bf288d) - This is completely based on my code
> * [29280fc](https://github.com/CCExtractor/taskwarrior-flutter/commit/29280fc48bbd255fd3a40a48ceaf7eefed5e3a93) - Here I have taken reference for only a simple thing as I couldn't able to solve that
> * [3d8f3e4](https://github.com/CCExtractor/taskwarrior-flutter/commit/3d8f3e49f636b4d2e29d68be35f50ad942ec8e72) - using the freeinc details it is made

**Comment by NishantSinghal19** [comment]
Also if you want any changes in the license and in the release or in readme , I am happy to do that

**Comment by bradyt** [comment]
I'm not sure I understand what "taken some reference", "completely", or "it is made", mean to you. I asked who is the author, and it seems you are avoiding the question. Consider telling me what you think "taken some reference" means.

Let's slow down, and try very straightforward questions. Let's start with a single file in the first commit. You added a file in this commit, with the following path, `lib/widgets/taskfunctions/projects.dart`. Who is the author of that file?

**Comment by NishantSinghal19** [comment]
That is yours code so i can say you are the author

**Comment by cfsmp3** [comment]
@bradyt do you have a specific ask here? If not I'll just close the ticket.

**Comment by wasamasa** [comment]
I'm not a lawyer, but @bradyt is suggesting that his code has been reused wholesale without proper attribution. This is not OK.

It's a license violation to reuse code without complying with its license. If you violate the license, you're not allowed to use the code covered by it. Therefore I see two ways forward:

- Either remove all code from the project owned by @bradyt 
- Or comply with the license by doing the following:
  - Clarify who owns which parts of the code using copyright notices with author names
  - Clarify which license applies to each file using either:
    - License header comments
    - SPDX identifier comments
    - A file categorizing every file in the project and how it's licensed
  - Fulfill the remaining requirements imposed by the license. Since the original code appears to be owned by @bradyt and has been licensed under GPL3, you need to use a GPL3-compatible license because the combination of your and his code is effectively GPL3. Might as well consider relicensing it to be GPL3 to avoid any confusion on the subject.

I like https://github.com/fsfe/reuse-tool for ensuring license compliance in a project. You can learn more about GPL3 on https://www.gnu.org/licenses/gpl-faq.html.

One complication is that @bradyt did not use copyright notices in the file, so that makes it harder to prove ownership and easier to make mistakes with author attribution.

**Comment by cfsmp3** [comment]
@wasamasa I already asked what the specific ask is here.

I'm not a lawyer, I have zero desire of getting one, and this being a summer project to have fun with I'd rather just archive it and move on than continue this "discussion".

In any case and with respect, if you're not the author please don't add noise to the issue.

Suddenly this went from a smooth project to a big deal. Within 3 days. This is not the way developers are supposed to interact.

**Comment by bradyt** [comment]
Please delete the appropriate commits, and anything resembling said nature of those commits. Please ensure that such are also deleted from all propagations, including relevant forks and clones.

> I'd rather just archive it

If you archive the repo prematurely, I fear that would have a negative effect on addressing the issue.

**Comment by cfsmp3** [comment]
> Please delete the appropriate commits,

Why? 
Aren't they based on GPL licensed code?

**Comment by cfsmp3** [comment]
Closing this since it seems to be being discussed somewhere else.
