### ISSUE TITLE
Editable fields should be clearly visible 

### ISSUE THREAD

**Issue by bhav-khurana** [CCExtractor/taskwarrior-flutter#67]
In the task details page, the fields which can be edited on clicking should be marked separately so that the user can know which field(s) are read only and which ones are editable.

We can do something like this

![Screenshot_2023-01-10-23-01-13-43_95710ad301893fdccf6b861c51c8d13a.jpg](https://user-images.githubusercontent.com/96694482/211622187-42157d6e-ed75-4e22-9d99-241cb9c1d04d.jpg)

**Comment by NishantSinghal19** [comment]
I don't think this look so good

**Comment by bhav-khurana** [comment]
@NishantSinghal19 what changes can I do then?

**Comment by sainideepanshu199** [comment]
> I don't think this look so good

i think we can add an edit button in appbar that links to another page to edit details of the task . and only allow editable field to be edited,. this looks more clean rather than adding edit button to all editable fields.
![image](https://user-images.githubusercontent.com/114583893/213103534-62a01e1c-35a0-4130-b764-9c67a0917c07.png)


please assign me this issue so that i can work on the edit page of the task.

**Comment by abhinav52000** [comment]
I want to contribute to this issue. If this is open kindly assign me.

**Comment by Pavel401** [comment]
This UI is updated in the current build.
So closing it now.
